# Generated by Django 5.2.7 on 2025-10-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitem',
            old_name='done',
            new_name='item_done',
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='name',
            new_name='item_name',
        ),
    ]
